name: Validate renovate config

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: "*.json"
