name: Validate renovate config

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - name: Validate renovate config
        run: |
          for file in *.json
          do
            if [ $file = 'package.json' ]; then
              continue
            fi
            echo "[CI] Validate: $file"
            RENOVATE_CONFIG_FILE=${file} npx --package renovate -c 'renovate-config-validator'
          done
